spring.application.name=logitrack
server.port=8081
server.servlet.context-path=/api

spring.datasource.url=${DB_URL:jdbc:postgresql://pg-344cf1e5-santiagogomezrojas2007-43b2.c.aivencloud.com:20146/defaultdb?sslmode=require}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_aqP6vyMJ3wBZnknzT0f}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ejecuta data.sql despues de que Hibernate cree las tablas (ddl-auto=update)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

app.jwt.secret=${JWT_SECRET:ClaveSecretaSuperSeguraParaLogiTrack2026SistemaDeInventario}
app.jwt.expiration-ms=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
